/*
 * winzox_io_rs.h - C ABI for the WinZOX 3.1.0 Rust IO port.
 *
 * Generated by hand to match the `#[unsafe(no_mangle)] extern "C"` entries
 * in `winzox-io-rs/src/ffi.rs`. Bump the ABI version constant whenever the
 * layout of any structure or the signature of any function changes.
 */
#ifndef WINZOX_IO_RS_H
#define WINZOX_IO_RS_H

#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef enum WinzoxIoStatus {
    WINZOX_IO_OK = 0,
    WINZOX_IO_NOT_FOUND = 1,
    WINZOX_IO_SYMLINK = 2,
    WINZOX_IO_UNSUPPORTED = 3,
    WINZOX_IO_FILE_TOO_LARGE = 4,
    WINZOX_IO_VOLUMES_TOO_LARGE = 5,
    WINZOX_IO_INVALID_UTF8 = 6,
    WINZOX_IO_IO = 7,
    WINZOX_IO_NULL_ARGUMENT = 8,
} WinzoxIoStatus;

typedef struct WinzoxIoBuffer {
    uint8_t* data;
    size_t   len;
    size_t   cap;
} WinzoxIoBuffer;

typedef struct WinzoxIoPathList {
    char*    data;       /* NUL-separated UTF-8 paths, NUL-terminated overall */
    size_t   byte_len;
    size_t   count;
} WinzoxIoPathList;

typedef struct WinzoxIoVolumeWriter WinzoxIoVolumeWriter;

/* Retrieve the most recent thread-local error message. NULL if none. */
const char*       winzox_io_last_error(void);

/* Release a buffer previously returned by this library. */
void              winzox_io_buffer_free(WinzoxIoBuffer buffer);

/* Release a path list previously returned by this library. */
void              winzox_io_path_list_free(WinzoxIoPathList list);

WinzoxIoStatus    winzox_io_read_file_bytes(const char* path,
                                            WinzoxIoBuffer* out_buffer);
WinzoxIoStatus    winzox_io_write_file_bytes(const char* path,
                                             const uint8_t* data,
                                             size_t len);
WinzoxIoStatus    winzox_io_read_all_volumes(const char* path,
                                             WinzoxIoBuffer* out_buffer);
WinzoxIoStatus    winzox_io_collect_input_files(const char* input_path,
                                                WinzoxIoPathList* out_list);

WinzoxIoStatus    winzox_io_volume_writer_new(const char* base_path,
                                              uint64_t split_size,
                                              WinzoxIoVolumeWriter** out_handle);
WinzoxIoStatus    winzox_io_volume_writer_write(WinzoxIoVolumeWriter* handle,
                                                const uint8_t* data,
                                                size_t len);
WinzoxIoStatus    winzox_io_volume_writer_close(WinzoxIoVolumeWriter* handle);
void              winzox_io_volume_writer_free(WinzoxIoVolumeWriter* handle);

int               winzox_io_abi_version(void);

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /* WINZOX_IO_RS_H */
